/**
 * Regenerate src/providers/pricing.generated.ts from https://models.dev/api.json.
 *
 * models.dev is the same source our capabilities table cites. We pull pricing
 * ONLY from first-party vendor providers (no aggregators like OpenRouter, whose
 * rates carry a margin), so the generated table reflects raw list prices.
 *
 * The generated table is a fallback in getPricingForModel — config.yaml /
 * dashboard overrides still win, and the hand-curated MODEL_PRICING covers
 * models models.dev doesn't list. Run: `npm run sync-pricing`.
 */
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const API = "https://models.dev/api.json";

// First-party vendors only, in priority order (first provider that lists a model
// id wins, so a model shared across providers takes the upstream vendor's price).
const PRIORITY = [
  "anthropic",
  "openai",
  "google",
  "xai",
  "deepseek",
  "mistral",
  "groq",
  "cohere",
  "google-vertex",
];

interface MdCost {
  input?: number | null;
  output?: number | null;
  cache_read?: number | null;
  cache_write?: number | null;
}
interface MdModel {
  id: string;
  cost?: MdCost | null;
}
interface MdProvider {
  models: Record<string, MdModel>;
}
type MdApi = Record<string, MdProvider>;

interface Pricing {
  input: number;
  output: number;
  cached?: number;
  cache_creation?: number;
}

async function main(): Promise<void> {
  process.stdout.write(`fetching ${API} …\n`);
  const res = await fetch(API);
  if (!res.ok) throw new Error(`models.dev returned ${res.status}`);
  const api = (await res.json()) as MdApi;

  const out: Record<string, Pricing> = {};
  let fromProvider: Record<string, number> = {};

  for (const provider of PRIORITY) {
    const p = api[provider];
    if (!p?.models) continue;
    for (const model of Object.values(p.models)) {
      const c = model.cost;
      if (!c || typeof c.input !== "number" || typeof c.output !== "number") continue;
      if (out[model.id]) continue; // a higher-priority vendor already set it
      const entry: Pricing = { input: c.input, output: c.output };
      if (typeof c.cache_read === "number") entry.cached = c.cache_read;
      if (typeof c.cache_write === "number") entry.cache_creation = c.cache_write;
      out[model.id] = entry;
      fromProvider[provider] = (fromProvider[provider] ?? 0) + 1;
    }
  }

  const ids = Object.keys(out).sort();
  const lines = ids.map((id) => {
    const e = out[id]!;
    const parts = [`input: ${e.input}`, `output: ${e.output}`];
    if (e.cached !== undefined) parts.push(`cached: ${e.cached}`);
    if (e.cache_creation !== undefined) parts.push(`cache_creation: ${e.cache_creation}`);
    return `  ${JSON.stringify(id)}: { ${parts.join(", ")} },`;
  });

  const counts = PRIORITY.filter((p) => fromProvider[p]).map((p) => `${p}:${fromProvider[p]}`).join(" ");
  const header =
    `// AUTO-GENERATED by scripts/sync-pricing.ts from ${API}\n` +
    `// Do NOT edit by hand — run \`npm run sync-pricing\` to refresh.\n` +
    `// Synced ${new Date().toISOString().slice(0, 10)} · ${ids.length} models · ${counts}\n` +
    `import type { Pricing } from "./pricing.js";\n\n` +
    `export const GENERATED_PRICING: Record<string, Pricing> = {\n`;

  const file = `${header}${lines.join("\n")}\n};\n`;

  const here = dirname(fileURLToPath(import.meta.url));
  const dest = join(here, "..", "src", "providers", "pricing.generated.ts");
  writeFileSync(dest, file);
  process.stdout.write(`wrote ${ids.length} models → ${dest}\n  ${counts}\n`);
}

main().catch((e) => {
  process.stderr.write(`sync-pricing failed: ${(e as Error).message}\n`);
  process.exit(1);
});
